name: astro-website
region: nyc
static_sites:
  - name: astro-website
    source_dir: /
    build_command: npm ci && npm run build
    output_dir: dist
    environment_slug: node-js
    github:
      repo: kevinrrichey/astro-website
      branch: main
      deploy_on_push: true  # Added to ensure push triggers deployment
    envs:
      - key: NODE_VERSION
        value: "18"
        scope: BUILD_TIME
    routes:
      - path: /